### PR TITLE
feat: rename assign unassign #419

### LINKED ISSUE #419: Rename `/assign` to `/start`, `/unassign` to `/stop`
The intent for this command is to represent when the bounty hunter is actively working on the task, vs trying to just "reserve" the task.

The bounty hunters should only be working on a single task at a time. They should not be able to be "reserving" tasks and then neglecting to do them. 

Example: https://github.com/ubiquity/ubiquity-dollar/issues/616#issuecomment-1613354667

Renaming the command can provide a hint to the bounty hunter that they must actively work on the task when they use the command.

### PR DESCRIPTION
**Pull request by starlitnightsky**
Resolves #419

- Test
https://github.com/starlitnightsky/Real-Estate/issues/11#issue-1764931704
- Test for skipping start
https://github.com/starlitnightsky/Real-Estate/issues/11#issuecomment-1604093932
- Test for help menu
https://github.com/starlitnightsky/Real-Estate/issues/11#issuecomment-1604094225

### CODE REVIEW

**Review by pavlovcik — CHANGES_REQUESTED** [review]
You need to update the help menu and other related functions. @Draeieg you might be able to QA this if it works already.

**Comment by starlitnightsky** [comment]
> You need to update the help menu and other related functions. @Draeieg you might be able to QA this if it works already.

I just updated and pushed.

**Review by starlitnightsky — COMMENTED** [review]
I just updated.

**Comment by pavlovcik** [comment]
The grammar doesn't make sense. You need to spend some time rewriting the messages instead of just doing a find-and-replace.

**Review by pavlovcik — CHANGES_REQUESTED** [review]
The grammar doesn't make sense. You need to spend some time rewriting the messages instead of just doing a find-and-replace.

You also didn't rename the variables in the code. 

It wastes your and our time and will take a lot longer for you to close out bounties if you ask for reviews without first checking your work and giving attention to detail.

**Comment by Draeieg** [comment]
I assume this isn't ready for QA yet

**Comment by pavlovcik** [comment]
Closed for inactivity.

**Pull request closed without merging**
