### PR TITLE
fix: renamed ubiquibot-config-default file

### LINKED ISSUE #725: Refactor default bot config from `json` to `ts`
Original [comment](https://github.com/ubiquity/ubiquibot/pull/670#discussion_r1306600068)

There is the [default bot config](https://github.com/ubiquity/ubiquibot/blob/development/ubiquibot-config-default.json). 

We want to able to add comments to the default bot config. We can't transform the config from `json` to `yml` or `jsonc` because it requires using `fs.readFile()` which causes issues on production netlify build.

What should be done:
- refactor the [default bot config](https://github.com/ubiquity/ubiquibot/blob/development/ubiquibot-config-default.json) from `json` to a plain `ts` file

### PR DESCRIPTION
**Pull request by Wholesomebruh**
Resolves #725

### CODE REVIEW

**Comment by Wholesomebruh** [comment]
@pavlovcik , please have a look at this.

**Review by rndquu — APPROVED** [review]
Works fine

@Wholesomebruh pls resolve the conflicts

**Comment by Wholesomebruh** [comment]
@rndquu  Thanks for updating . "Resolve conflicts" button is disabled on my side, any idea how to work around?

**Comment by rndquu** [comment]
> @rndquu Thanks for updating . "Resolve conflicts" button is disabled on my side, any idea how to work around?

Manually merge the latest `development` branch via `git cli`, resolve the conflicts and push the update

**Comment by Wholesomebruh** [comment]
@rndquu , do we have a fixed value for this https://github.com/Wholesomebruh/ubiquibot/blob/96af7a57deacbd581a1c35dc05969581e023516e/src/types/config.ts#L193 as this must be added to default-config ?

**Comment by Wholesomebruh** [comment]
@rndquu , do we have a fixed value for "stale-bounty-time" , here https://github.com/ubiquity/ubiquibot/blob/development/src/types/config.ts#L193 ? This property must be added to default-config.

**Pull request closed without merging**
