### PR TITLE
Automatic migration

### LINKED ISSUE #504: Create a github action to run the migrations automatically
### Describe the background or context

Whenever we create a new migration, it needs to be applied to the supabase. 
It's currently being done manually but the ideal solution is to run the migration in github action automatically.

### Describe the solution

- [ ] Add a new step in [build.yml](https://github.com/ubiquity/ubiquibot/blob/development/.github/workflows/build.yml) called Run migration.
- [ ] Create separate secrets for production/staging(main/development) and use them in the step.

**_NOTE_** You can refer the [README.md](https://github.com/ubiquity/ubiquibot/blob/development/supabase/README.md) how to run the migration

### PR DESCRIPTION
**Pull request by whilefoo**
Resolves #504

### CODE REVIEW

**Comment by pavlovcik** [comment]
Perhaps you can link successful GitHub Action logs?

**Comment by whilefoo** [comment]
https://github.com/whilefoo/ubiquibot/actions/runs/5562861742

**Comment by pavlovcik** [comment]
Looks good! The only thing that seems a little suspicious to me is that it said it failed to save a database password or something. I presume that it won't be an issue?

https://github.com/whilefoo/ubiquibot/actions/runs/5562861742/jobs/10161500340#step:4:10

**Comment by whilefoo** [comment]
> it failed to save a database password or something. I presume that it won't be an issue?

It's only complaining about that because we are running this in CI

**Review by pavlovcik — APPROVED** [review]

**Review by 0xcodercrane — APPROVED** [review]
Looks good. Let me merge it once I finish the secrets setup

**Comment by 0xcodercrane** [comment]
added secrets. merging

**Pull request merged**
