### PR TITLE
chore: updated most bot error messages

### LINKED ISSUE #741: Change Permit Generation Error Messages
> Permit generation skipped since the issue is identified as parent issue.

Should be instead:

Permit generation disabled because this is a collection of issues. 

---

I think for all the similar messages, we should say: 
- "disabled" instead of "skipped" 
- "because" instead of "since"

And ensure punctuation at the end of every message.

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquity/telegram-ubiquibot/issues/2#issuecomment-1712862573_

### PR DESCRIPTION
**Pull request by EtherealGlow**
Resolves #741

### CODE REVIEW

**Review by pavlovcik — CHANGES_REQUESTED** [review]
No "!" punctuation

**Comment by EtherealGlow** [comment]
Just .?

**Comment by Wholesomebruh** [comment]
@EtherealGlow , this issue is already merged with my PR, still you got the bounty, is there any way we can settle this? Please.

**Comment by EtherealGlow** [comment]
Idek what to do, maybe ask pavlockik?

**Comment by Wholesomebruh** [comment]
@EtherealGlow Have you collected the reward?

**Comment by EtherealGlow** [comment]
But I also did the spec

**Comment by Wholesomebruh** [comment]
@EtherealGlow What if I propose, you collect the reward and share half with me? I raised PR earlier , and mine was the one that closed the issue.

**Comment by EtherealGlow** [comment]
Aight idc

**Comment by EtherealGlow** [comment]
https://gnosisscan.io/tx/0x5946a6ed15f8b4d8775065a593b8162e1c87dc103f1dae77a1c3d0d55e41b4e1

**Pull request closed without merging**
