### PR TITLE
fix: hotfix to local build

### LINKED ISSUE #796: [local development bug] yarn build generates /lib/index.js instead of /lib/src/index.js
just did a clean install and I get another error upon yarn start: Cannot find module './lib/src/index.js'. it seems Typescript is generating ./lib/index.js instead of ./lib/src/index.js. Not sure why it changed

Originally from telegram: by @whilefoo https://t.me/UbiquityDAO/31132/31145

### PR DESCRIPTION
**Pull request by molecula451**
Resolves #796 

Quality Assurance: 

https://github.com/ubiquity/ubiquibot/issues/796#issuecomment-1730921561

latest branch development, on quick `yarn build`, puts `index.js` outside `/src` folder

```typescript
$ probot run ./lib/index.js
INFO (probot): 
INFO (probot): Welcome to Probot!
INFO (probot): Probot is in setup mode, webhooks cannot be received and
INFO (probot): custom routes will not work until APP_ID and PRIVATE_KEY
INFO (probot): are configured in .env.
INFO (probot): Please follow the instructions at http://localhost:3000 to configure .env.
INFO (probot): Once you are done, restart the server.
INFO (probot): 
INFO (server): Running Probot v12.3.1 (Node.js: v20.6.1)
INFO (server): Forwarding https://smee.io/lIAqkpXtACUt1U10 to http://localhost:3000/
INFO (server): Listening on http://localhost:3000
INFO (server): Connected
```

### CODE REVIEW

**Comment by molecula451** [comment]
we could also make a new command `start:local`

**Comment by molecula451** [comment]
it's possible also that https://github.com/ubiquity/ubiquibot/blob/16aaa179832c09532822ccd361be4bc07835fcc8/package.json#L17

it's copying everything including `index.js` back to /lib

**Comment by molecula451** [comment]
https://github.com/ubiquity/ubiquibot/issues/796#issuecomment-1731268558

**Review by whilefoo — CHANGES_REQUESTED** [review]
Can you also fix an error that happens during analytics. `lib/assets/images` folder doesn't get created and also `flat.png` doesn't get copied in `images` folder

```js
[Error: ENOENT: no such file or directory, open '/Users/whilefoo/ubiquity/ubiquibot/lib/assets/images/pmg.png'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/whilefoo/ubiquity/ubiquibot/lib/assets/images/pmg.png'
}
```

**Comment by molecula451** [comment]
> lib/assets/images

there is no such thing as `lib/assets/images` but

about `flat.png`, it gets to `/src/assets/images` it's there

**Comment by molecula451** [comment]
> > lib/assets/images
> 
> there is no such thing as `lib/assets/images` but
> 
> about `flat.png`, it gets to `/src/assets/images` it's there

also I see you're on Node on Windows, it might be interesting to reproduce this there

**Comment by molecula451** [comment]
> > > lib/assets/images
> > 
> > 
> > there is no such thing as `lib/assets/images` but
> > about `flat.png`, it gets to `/src/assets/images` it's there
> 
> also I see you're on Node on Windows, it might be interesting to reproduce this there with a new issue

**Comment by molecula451** [comment]
let's get this merge as there are tasks that requires it #291

3 people having this issue

Me
While
Serprintour

**Comment by whilefoo** [comment]
> there is no such thing as `lib/assets/images` but
> 
> about `flat.png`, it gets to `/src/assets/images` it's there

that's literally the problem. `lib/assets/images` should exist and `flat.png` should be copied in there.



> also I see you're on Node on Windows, it might be interesting to reproduce this there with a new issue

I'm on MacOS. This is a problem we had before so I know it's reproducible.

**Comment by molecula451** [comment]
> > there is no such thing as `lib/assets/images` but
> > 
> > about `flat.png`, it gets to `/src/assets/images` it's there
> 
> that's literally the problem. `lib/assets/images` should exist and `flat.png` should be copied in there.
 
flat.png it's there

**Comment by molecula451** [comment]
> > there is no such thing as `lib/assets/images` but
> > 
> > about `flat.png`, it gets to `/src/assets/images` it's there
> 
> that's literally the problem. `lib/assets/images` should exist and `flat.png` should be copied in there.
> 
> 
> 
> > also I see you're on Node on Windows, it might be interesting to reproduce this there with a new issue
> 
> I'm on MacOS. This is a problem we had before so I know it's reproducible.

In your case i see You are not Even getting a src folder. Try a Ubuntu docker

**Comment by whilefoo** [comment]
> In your case i see You are not Even getting a src folder. Try a Ubuntu docker

What do you mean? I have `src` folder and I'm running the bot after I create `lib/assets/images/flat.png` just fine.

**Comment by whilefoo** [comment]
> flat.png it's there

flat.png is not in `lib/assets/images`

**Comment by molecula451** [comment]
> > In your case i see You are not Even getting a src folder. Try a Ubuntu docker
> 
> What do you mean? I have `src` folder and I'm running the bot after I create `lib/assets/images/flat.png` just fine.

You got `lib/src/assets/images`?

**Comment by molecula451** [comment]
> > flat.png it's there
> 
> flat.png is not in `lib/assets/images`

It is mate can't reproduce this one. I reproduce the original for the PR

**Comment by whilefoo** [comment]
> > > In your case i see You are not Even getting a src folder. Try a Ubuntu docker
> > 
> > 
> > What do you mean? I have `src` folder and I'm running the bot after I create `lib/assets/images/flat.png` just fine.
> 
> You got `lib/src/assets/images`?

After I run `yarn build`, `lib/assets` gets created but `lib/assets/images` folder doesn't.

**Comment by pavlovcik** [comment]
> that's literally the problem. `lib/assets/images` should exist and `flat.png` should be copied in there.

We can remove this entirely its for a partially implemented feature for weekly updates on Telegram. Maybe this one #108

**Comment by molecula451** [comment]
The thing is to me is aother issue because Whilefool has it but cannot reproduce but i can reproduce the original to the PR

**Review by whilefoo — APPROVED** [review]
let's get this merged and create a separate isssue for another bug

**Pull request merged**
