### PR TITLE
feat: add first time configs

### LINKED ISSUE #96: Add first time contributor message
# Specification

The two business problems to solve are: 

1. a custom message that partners can use to greet new hunters
2. show a list of all of the bot commands that the new hunter can invoke.

We must create new config properties: 
- [ ] `FIRST_TIME_CONTRIBUTOR_GREETING_HEADER`: string;
- [ ] `FIRST_TIME_CONTRIBUTOR_GREETING_HELP_MENU`: boolean;
- [ ] `FIRST_TIME_CONTRIBUTOR_GREETING_FOOTER`: string;

Post the header first, then the help menu, and lastly the footer in a single "first time contributor greeting" comment.

- [ ] Be sure to also update the README.md with these config properties.

# Example Input

```
FIRST_TIME_CONTRIBUTOR_GREETING_HEADER="Thank you for contributing to UbiquiBot! Please be sure to set your wallet address before completing your first bounty so that the automatic payout upon task completion will work for you."
FIRST_TIME_CONTRIBUTOR_GREETING_HELP_MENU=true
FIRST_TIME_CONTRIBUTOR_GREETING_FOOTER="###### Also please star this repository and [@ubiquity/devpool-directory](https://github.com/ubiquity/devpool-directory/) to show your support. It helps a lot!"
```

# Example Output

Thank you for contributing to UbiquiBot! Please be sure to set your wallet address before completing your first bounty so that the automatic payout upon task completion will work for you. 

```
- /assign: Assign the origin sender to the issue automatically.
- /unassign: Unassign the origin sender from the issue automatically.
- /help: List all available commands.
- /payout: Disable automatic payment for the issue.
- /multiplier: Set bounty multiplier (for treasury)
- /allow: Set access control. (Admin Only)
- /wallet: <WALLET_ADDRESS | ENS_NAME>: Register the hunter's wallet address. 
  ex1: /wallet 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 
  ex2: /wallet vitalik.eth
```

### PR DESCRIPTION
**Pull request by EtherealGlow**
Resolves #96

### CODE REVIEW

**Comment by EtherealGlow** [comment]
i might have not done everything fully, if yes, please let me know

**Review by rndquu — CHANGES_REQUESTED** [review]
1. Pls refactor param names to kebab case, example: `first-time-contributer-greeting-help-menu`
2. The `first-time-contributer-greeting-footer` param is missing
3. Pls fix the spelling `contributer => contributor`

**Comment by web4er** [comment]
This is missing a QA. Please [add a QA](https://github.com/ubiquity/ubiquibot#how-to-qa-any-additions-to-the-bot).

**Review by rndquu — DISMISSED** [review]

**Review by pavlovcik — APPROVED** [review]
Code looks good!

**Comment by Draeieg** [comment]
[QA](https://github.com/ubiquibot/staging/issues/102) is failing @EtherealGlow 


plz link an QA issue where you show it works and explain the exact scenarios in which the bot will generate this reply

**Comment by rndquu** [comment]
> [QA](https://github.com/ubiquibot/staging/issues/102) is failing @EtherealGlow
> 
> plz link an QA issue where you show it works and explain the exact scenarios in which the bot will generate this reply

This "first time contributor" message should be displayed literally in response to the 1st bounty hunter's comment in a repo

This [QA](https://github.com/ubiquibot/staging/issues/102) tries to get the "first time contributor" message for `devtestubq` account but this is not the 1st message of `devtestubq`. This account had already [posted](https://github.com/ubiquibot/staging/issues/87#issuecomment-1664599199) messages earlier.

So to QA the current issue we need a fresh account without any comments.

**Comment by EtherealGlow** [comment]
oops

**Comment by EtherealGlow** [comment]
accidentally pushed to wrong branch

**Comment by EtherealGlow** [comment]
i am very sorry about this

**Pull request closed without merging**
