### PR TITLE
feat: follow up with reviewer

### LINKED ISSUE #324: The bot should follow up with the pending reviewer (using the same 3-4 day timeout logic) inside of the pull request.

### PR DESCRIPTION
**Pull request by EtherealGlow**
Resolves #324

Quality Assurance: https://github.com/EtherealGlow/ubiquibot/pull/27

### CODE REVIEW

**Comment by EtherealGlow** [comment]
#783

**Review by whilefoo — CHANGES_REQUESTED** [review]
you have error in build workflow

**Comment by EtherealGlow** [comment]
I didn't even see it

**Comment by EtherealGlow** [comment]
Fixing it rn

**Pull request closed without merging**
