### PR TITLE
feat: rollout the new version

### PR DESCRIPTION
**Pull request by 0xcodercrane**

### CODE REVIEW

**Comment by pavlovcik** [comment]
Looks like CI/CD is broken so I'll review when its ready to review lol

**Comment by 0xcodercrane** [comment]
> Looks like CI/CD is broken so I'll review when its ready to review lol

Looks like checksum issue in yarn.lock. Let me regenerate it and push

**Comment by 0xcodercrane** [comment]
CI/CD fixed on netlify

**Comment by 0xcodercrane** [comment]
https://github.com/ubiquity/bounty-bot/pull/266 --- QA not passed

**Pull request merged**
