### PR TITLE
Feat/max bounty issue improvement fixed

### LINKED ISSUE #298: Max bounty hunter issues improvement
An improvement idea is to check all of the open pull requests of the bounty hunter, and then check the state of the pull request review. 

If they have a pull request open but no review started, then it counts against their quota. 

If they have a pull request opened and also have a "review" in progress (perhaps there is an api to get a Boolean for this) then they are able to start working on another bounty. 

Next level beyond could be a 
one day "cool down". If there's longer than a 24 hour delay by the core team/reviewers, then "unlock" the bounty hunter to work on another issue. 

_Originally posted by @pavlovcik in https://github.com/ubiquity/bounty-bot/issues/245#issuecomment-1541195579_

### PR DESCRIPTION
**Pull request by wannacfuture**
# Description

- added feat: max bounty issue improvement(counts opened prs with no reviews)

closes #298

### CODE REVIEW

**Review by pavlovcik — APPROVED** [review]
Code looks good. You achieved the specification, thanks for that, but I think I will like to create a new bounty to make the 24 hour period configurable (this also means we need to add a new config property.

**Comment by wannacfuture** [comment]
> Code looks good. You achieved the specification, thanks for that, but I think I will like to create a new bounty to make the 24 hour period configurable (this also means we need to add a new config property.

Could you provide me detailed information?

**Comment by wannacfuture** [comment]
> > Code looks good. You achieved the specification, thanks for that, but I think I will like to create a new bounty to make the 24 hour period configurable (this also means we need to add a new config property.
> 
> Could you provide me detailed information? If you create another new bounty about it, I'll also handle it.

**Review by rndquu — APPROVED** [review]

**Review by 0xcodercrane — APPROVED** [review]

**Comment by pavlovcik** [comment]
If our new standard operating procedure is to request a QA test from @Draeieg then the last person to approve (@0xcodercrane) should request for a review from @Draeieg after the code checks out.

**Comment by wannacfuture** [comment]
Seems your new standard operating procedure is too perfect.😅 @Draeieg , Could you review this PR?

**Comment by Draeieg** [comment]
> Seems your new standard operating procedure is too perfect.😅 @Draeieg , Could you review this PR?

I need @0xcodercrane merge this to development  in order to do my QA run 

Also, we're going to implement #391, reducing the bureaucracy

**Comment by wannacfuture** [comment]
Ah.. so, should I install QA app to my forked repo? And what should I do?
I can't get that meaning exactly. Could you explain in detail?

**Comment by Draeieg** [comment]
> Ah.. so, should I install QA app to my forked repo? And what should I do?
> I can't get that meaning exactly. Could you explain in detail?

The current plan is: Install the QA app on your forked repo, run the github action, and you should have the bot running with local changes

Then, open issues to test the code changes (by example in this case, you can open 3 assign to 2 then request for a review from yourself and then see if you can assign the third)

We're literally just releasing this, so if something sounds confusing or is not working, be sure to notify

**Comment by wannacfuture** [comment]
> > Ah.. so, should I install QA app to my forked repo? And what should I do?
> > I can't get that meaning exactly. Could you explain in detail?
> 
> The current plan is: Install the QA app on your forked repo, run the github action, and you should have the bot running with local changes
> 
> Then, open issues to test the code changes (by example in this case, you can open 3 assign to 2 then request for a review from yourself and then see if you can assign the third)
> 
> We're literally just releasing this, so if something sounds confusing or is not working, be sure to notify

Actually, I have tested my PR on my local repository and it worked. Should I send that screenshot or something...?

**Review by Draeieg — APPROVED** [review]

**Pull request merged**
