### PR TITLE
Comment incentives nonce

### LINKED ISSUE #686: Use different nonce for comment incentives
### Context

Check this [issue](https://github.com/ubiquity/ubiquity-dollar/issues/780)

There are 2 permits generated:
1. https://github.com/ubiquity/ubiquity-dollar/issues/780#issuecomment-1696422095 (issue solver reward)
2. https://github.com/ubiquity/ubiquity-dollar/issues/780#issuecomment-1696422165 (issue creator reward)

Right now we use `issue.node_id` as a permit nonce so those 2 permits are using the same nonce. It means that only 1 of those permits is claimable.

We should change the logic of how permit nonce is generated so that the permit (bounty reward + comment incentives) could be claimed by different bounty hunters in a single issue. 

Perhaps we could generate nonce smth like `keccak256(issue.node_id . bountyHunter.user_id)`.

### Tasks

1. Consolidate the permits based on contributor (right now there can be multiple posted for a single contributor.)
    - When combined, the caption should list out all of the reasons. e.g. "Issue creator, and assignee rewards: "
2. Use the issue ID and user ID for the nonce. 
    - This enforces that a contributor can only get paid out one time per issue.

### PR DESCRIPTION
**Pull request by devpanther**
Resolves #686

QA: https://github.com/one-two-test/one/issues/6

### CODE REVIEW

**Comment by rndquu** [comment]
Ok, so there is a [QA](https://github.com/rndquu-org/test-repo/issues/7) and the result is:
1. Conversation rewards are [empty](https://github.com/rndquu-org/test-repo/issues/7#issuecomment-1699896537)
2. Issue creator reward is not generated

I feel like we won't be on time with the "reward consolidation" feature (keeping in mind that the demo is tomorrow)

@devpanther As as part of this issue could apply only the new nonce [generation logic](https://github.com/ubiquity/ubiquibot/issues/686#issuecomment-1698878812)? It should be enough for the demo.

We will move the "bounty consolidation" feature in a separate bounty

**Comment by devpanther** [comment]
> We will move the \"bounty consolidation\" feature in a separate bounty

That's not an issue with the branch, it's most likely incentivizeMode off or other issues I faced myself while trying to test on my repo.. 

So let's use a fully setup QA repo, you can try running development code on your repo and see if it's generated too

**Comment by devpanther** [comment]
@rndquu try adding `comment-incentives` as true in your yml file and try this again

**Comment by devpanther** [comment]
`payment-permit-max-price` should also be greater than 0

**Comment by devpanther** [comment]
And btw, conversations reward is not generated for assigned user anymore

https://github.com/ubiquity/ubiquibot/issues/686#issuecomment-1699112183

**Comment by devpanther** [comment]
You also don't have incentives object in either of your yml files

```json
incentives:
  comment:
    elements:
      code: 20
      img: 5
      h1: 1
      li: 0.5
      blockquote: 0
    totals:
      word: 0.1
```

**Comment by rndquu** [comment]
@devpanther 

1. Check this [QA](https://github.com/rndquu-org/test-repo/issues/14). Why task creator reward is missing? 
2. Check this [QA](https://github.com/rndquu-org/test-repo/issues/16). [Task creator](https://github.com/rndquu-org/test-repo/issues/16#issuecomment-1701057267) and [conversation](https://github.com/rndquu-org/test-repo/issues/16#issuecomment-1701057179) rewards should've been consolidated.

Overall, let move reward consolidation feature to a separate issue, pls only [fix the nonces](https://github.com/ubiquity/ubiquibot/issues/686#issuecomment-1698878812) in the current issue

**Comment by devpanther** [comment]
@rndquu rollback to nonce only fix done

**Comment by rndquu** [comment]
> @rndquu rollback to nonce only fix done

Thank you, I'll check it in 2 hours

**Review by rndquu — APPROVED** [review]
[QA](https://github.com/rndquu-org/test-repo/issues/21) is fine, nonces are unique

**Review by 0xcodercrane — CHANGES_REQUESTED** [review]

**Review by 0xcodercrane — APPROVED** [review]

**Pull request merged**
