### PR TITLE
Hotfix: close pr when unassigned hotfix

### PR DESCRIPTION
**Pull request by wannacfuture**
hotfix for getPullRequests pagination

### CODE REVIEW

**Review by pavlovcik — CHANGES_REQUESTED** [review]
Accidental wrong review result type

**Comment by wannacfuture** [comment]
> Accidental wrong review result type

I can't understand ..🙄

**Review by web4er — APPROVED** [review]
The code looks good to me. 
Here I have reproduced the issue and also tested it after this fix https://github.com/web4er/ubiquibot/issues/61 Appears to be working fine.
The QA was performed by hardcoding `per_page` parameter of fetching the PRs list. Not super reliable but I think it is helpful.

**Review by pavlovcik — APPROVED** [review]
I am mostly going off of @web4er's QA test! Thanks for the speedy QA.

**Comment by pavlovcik** [comment]
@0xcodercrane please prioritize getting this into production.

**Pull request merged**
