### PR TITLE
Bounty fix reassign

### LINKED ISSUE #403: Expired Bounties Remain Un-assignable
It appears that when bounties time out that they are no longer assignable to any hunter. This is disrupting to our operations and must be fixed.

1. I do like the idea of restricting bounty hunters from re-assigning themselves (it is their responsibility to provide regular and timely updates.) 
2. I do not like that the bot refuses to leave timed-out bounties assigned as you can see in my linked example:

              Releasing the bounty back to dev pool because the allocated duration already ended!

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquity/card-issuance/issues/9

### PR DESCRIPTION
**Pull request by devpanther**
Resolves #403

### CODE REVIEW

**Review by 0xcodercrane — COMMENTED** [review]
No comments for code changes. hope @Draeieg give a green light in QA.

**Comment by devpanther** [comment]
> No comments for code changes. hope @Draeieg give a green light in QA.

I don't understand what you mean comments for code changes, it was a fix (mainly using another function that gets all comments and removed the stale function that doesn't fetch all available comment)

**Comment by pavlovcik** [comment]
> No comments for code changes. hope @Draeieg give a green light in QA.

You need to request a review from @Draeieg when it's ready for QA

**Comment by Draeieg** [comment]
> Does the QA even work, why's going weeks without updates.. now there's conflicts

It seems at some point our pr template got messed up. Sorry for the delays caused by that 

You're required to link a QA done under your own forked repo (not in our staging environment) as indicated in the Readme together with the initial PR

This pr requires setting a preview for a few days while bounties time out. As a result, I had to leave it last in the list. Otherwise, testing the other 10 open wouldn't be possible 

I just got started testing it, I'll aprove if it passes initial testing due to the time it has taken

I'll ping you if some issues pop out while doing more thorough testing

**Comment by devpanther** [comment]
> > Does the QA even work, why's going weeks without updates.. now there's conflicts
> 
> It seems at some point our pr template got messed up. Sorry for the delays caused by that
> 
> You're required to link a QA done under your own forked repo (not in our staging environment) as indicated in the Readme together with the initial PR
> 
> This pr requires setting a preview for a few days while bounties time out. As a result, I had to leave it last in the list. Otherwise, testing the other 10 open wouldn't be possible
> 
> I just got started testing it, I'll aprove if it passes initial testing due to the time it has taken
> 
> I'll ping you if some issues pop out while doing more thorough testing

Following up

**Comment by devpanther** [comment]
> > Does the QA even work, why's going weeks without updates.. now there's conflicts
> 
> It seems at some point our pr template got messed up. Sorry for the delays caused by that
> 
> You're required to link a QA done under your own forked repo (not in our staging environment) as indicated in the Readme together with the initial PR
> 
> This pr requires setting a preview for a few days while bounties time out. As a result, I had to leave it last in the list. Otherwise, testing the other 10 open wouldn't be possible
> 
> I just got started testing it, I'll aprove if it passes initial testing due to the time it has taken
> 
> I'll ping you if some issues pop out while doing more thorough testing

Following up @Draeieg

**Review by Draeieg — APPROVED** [review]

**Pull request merged**
