### PR TITLE
hotfix: change devpool repo name

### PR DESCRIPTION
**Pull request by devpanther**

### CODE REVIEW

**Comment by devpanther** [comment]
@pavlovcik related to https://github.com/ubiquity/devpool-directory-bounties/issues/10

**Review by pavlovcik — APPROVED** [review]

**Comment by devpanther** [comment]
@pavlovcik when does it reflect on the `UbiquiBot`... is it while its on `development` or `main` because it still does not work

**Comment by pavlovcik** [comment]
`main` goes on the production bot but those usually are rolled out 1-2 times a month.

**Comment by devpanther** [comment]
> `main` goes on the production bot but those usually are rolled out 1-2 times a month.

So the change i made won't actually reflect until it is rolled out, I tried to install a new app just now and it seems its still getting the repo name wrong

**Comment by pavlovcik** [comment]
rfc @rndquu @0xcodercrane

**Comment by rndquu** [comment]
@devpanther I don't understand how the current PR solves the original [issue](https://github.com/ubiquity/devpool-directory-bounties/issues/10). This "create PR" [script](https://github.com/devpanther/bounty-bot/blob/7344b9ee275e57174a9f71d0daeb593df9c9ea6b/src/handlers/pull-request/create-devpool-pr.ts) will work both for `devpool` and `devpool-directory` because https://github.com/ubiquity/devpool redirects https://github.com/ubiquity/devpool-directory.

This "unexpected" [issue](https://github.com/ubiquity/devpool-directory/issues/734) was created because the [sync workflow run for a closed PR](https://github.com/ubiquity/devpool-directory/blob/development/.github/workflows/sync-issues.yml#L6) if it was not [merged](https://github.com/ubiquity/devpool-directory/pull/732). So we should refactor the sync workflow to run **only** on push to the `development` branch.

**Comment by devpanther** [comment]
> @devpanther I don't understand how the current PR solves the original issue

It doesn't run anymore and I don't think it's redirecting.. Because new installations don't trigger anymore so this is suppose to help that

**Comment by devpanther** [comment]
And then I'd be able to install on my organization and figure out when the workflow runs.. But like you said it runs on PR closed so that's that issue there

But this repo name still needs to be changed

**Pull request merged**
