### PR TITLE
Merge Refactor/move to delegated compute into Development

### LINKED ISSUE #927: Debug Admin Only Permit Generation
> I wonder if it's worth debugging why only admins can generate permits on v1 bot. 

_Originally posted by @0x4007 in https://github.com/ubiquity/work.ubq.fi/issues/41#issuecomment-2108901126_

### PR DESCRIPTION
**Pull request by gentlementlegen**
Resolves #927

@0x4007 @gitcoindev Re-opening the same PR here just to have develop up-to-date and the issue closed.

### CODE REVIEW

**Comment by gentlementlegen** [comment]
@0x4007 Or should have I not merged? Dunno what is the status of develop against this branch, sorry about that.

**Comment by 0x4007** [comment]
It's fine unless something breaks lol

**Comment by gentlementlegen** [comment]
@0x4007 Major change is yarn -> bun. Code base seems to follow the same logic. Let's see if the deployment fails, I'll revert.

**Comment by 0x4007** [comment]
https://github.com/ubiquity/ubiquibot/commit/bc4baaf2a9c9b4f3e899ba28ec2494f446360ff9#commitcomment-142323292

**Comment by gentlementlegen** [comment]
> [bc4baaf#commitcomment-142323292](https://github.com/ubiquity/ubiquibot/commit/bc4baaf2a9c9b4f3e899ba28ec2494f446360ff9#commitcomment-142323292)

@0x4007  Should this mean I should revert? Or just update that file back with all the data

**Comment by 0x4007** [comment]
Just revert the value to what it was originally.

**Comment by gentlementlegen** [comment]
@0x4007 Yep this is done. Also the fix I made should go in. Can revert `bun` update if you want, it was for me to be able to run on Windows, previous version doesn't work.

**Comment by 0x4007** [comment]
No comment on bun

**Comment by gentlementlegen** [comment]
@0x4007 Ran this version inside my own repo for testing, commands seem to respond fine.
https://github.com/Meniole/bot/issues/4#issuecomment-2133152807
This version should be working and safe to merge!

**Comment by 0x4007** [comment]
Check the files view at the bottom. There's an [e2e test error](https://github.com/ubiquity/ubiquibot/actions/runs/9210992288) related to config!

Also somehow Knip reporter has been [running for six days](https://github.com/ubiquity/ubiquibot/runs/25339306022)...not sure how that is possible @gitcoindev 👀

Screenshot 2024-05-30 at 15 05 38

**Comment by gitcoindev** [comment]
> Check the files view at the bottom. There's an [e2e test error](https://github.com/ubiquity/ubiquibot/actions/runs/9210992288) related to config!
> 
> Also somehow Knip reporter has been [running for six days](https://github.com/ubiquity/ubiquibot/runs/25339306022)...not sure how that is possible @gitcoindev 👀
> 
> Screenshot 2024-05-30 at 15 05 38

lol let me check this. Six hours should be maximum but normally it takes less than 1 second to execute.

**Comment by gitcoindev** [comment]
@0x4007 @gentlementlegen I found a most likely cause for the six days run mentioned above - the knip commands were incorrect in `package.json` and the wokrflow was in a busy loop. The incorrect commands look like an integration error in one of the previous prs. I fixed this and opened https://github.com/ubiquity/ubiquibot/pull/933 . Knip is supposed to fail with findings in this repo and as discussed with @rndquu we will not fix it here since this repo is deprecated, but Knip workflow itself was fixed to avoid leaking secrets with potential malicious pull requests.

**Comment by gitcoindev** [comment]
For this PR I am not sure about configuration error https://github.com/ubiquity/ubiquibot/actions/runs/9210992288/job/25339291201?pr=929 @gentlementlegen could you please share any information on that?

**Comment by gentlementlegen** [comment]
@gitcoindev Seems that during the tests, `env` variables were not populated as seen [here](https://github.com/ubiquity/ubiquibot/actions/runs/9210992288/job/25339291201?pr=929#step:6:16)

So when the configuration is tested it fails as it is undefined.

**Review by 0x4007 — APPROVED** [review]

**Pull request merged**
