### PR TITLE
Fix:Log-app code seperated and github workflow is assigned

### LINKED ISSUE #712: Move `log-app` to a separate repository
There is the frontend [log application](https://github.com/ubiquity/ubiquibot/tree/development/log-app) which displays all of the logs produced by the bot. 

We should move it to a separate repository in order not to: 
- mess log and bot deploy scripts together
- apply a shared cloudflare pages deploy [workflow](https://github.com/ubiquity/.github/blob/main/.github/workflows/deploy.yml)

What should be done:
1. Move the [log app](https://github.com/ubiquity/ubiquibot/tree/development/log-app) to a separate repo
2. Remove the log app's related code from the https://github.com/ubiquity/ubiquibot repo
3. Deploy the log app to cloudflare pages using this [workflow](https://github.com/ubiquity/.github/blob/main/.github/workflows/deploy.yml)

P.S. When we are done moving the log app to a separate repo we should configure stage and prod [supabase API keys](https://github.com/ubiquity/ubiquibot/blob/development/log-app/scripts/constants/index.ts).

### PR DESCRIPTION
**Pull request by baibhavKumar1**
Resolves #712 
Don't merge before creation of new "log-app" repo.
1) Creating a new repo is beyond my access for this org. Once the repo is created by owner, I can add the log-app folder to new repository.
2) Log-app and ubiquibot code has been seperated.
3) Workflow is assigned accordingly.

### CODE REVIEW

**Comment by pavlovcik** [comment]
I created the repository for you. Please feel free to introduce changes via a pull request there!

https://github.com/ubiquity/ubiquibot-logging

**Comment by Wholesomebruh** [comment]
> I created the repository for you. Please feel free to introduce changes via a pull request there!
> 
> https://github.com/ubiquity/ubiquibot-logging

Thanks, on it ser.

**Comment by Wholesomebruh** [comment]
@pavlovcik any idea, where "Fetcher" in https://github.com/ubiquity/ubiquibot/blob/development/log-app/types/global.ts is coming from, and "request" in https://github.com/ubiquity/ubiquibot/blob/development/log-app/_worker.ts ?

**Comment by rndquu** [comment]
> @pavlovcik any idea, where "Fetcher" in https://github.com/ubiquity/ubiquibot/blob/development/log-app/types/global.ts is coming from, and "request" in https://github.com/ubiquity/ubiquibot/blob/development/log-app/_worker.ts ?

I guess those types are coming from this [line](https://github.com/ubiquity/ubiquibot/blob/b3667b8b5487dc7651734fd7849718242f9cc3f2/log-app/tsconfig.json#L14). [Log app](https://github.com/ubiquity/ubiquibot/tree/development/log-app) uses a separate [tsconfig](https://github.com/ubiquity/ubiquibot/blob/development/log-app/tsconfig.json) so perhaps your IDE fetches the bot's [tsconfig](https://github.com/ubiquity/ubiquibot/blob/development/tsconfig.json) instead of the log app's one hence there are typescript errors in the IDE.

**Comment by rndquu** [comment]
@Wholesomebruh 

So this [PR](https://github.com/ubiquity/ubiquibot-logging/pull/1) creates the log app in a separate repo.

What about removing the log app from the bot's code? Is it implemented?

**Comment by Wholesomebruh** [comment]
It will be removed only after log-app is added to the logging repo, as there are few issues like #676 that will be adding changes to log-app . I will coordinate with contributer/hunter at time of final commit , if they want me to wait and add their changes also or they will make contribution to logging repo later. In this PR, there is log-app has no code connected with ubiquibot repo (other than .deployment [file](https://github.com/ubiquity/ubiquibot/blob/development/.github/workflows/deploy-logger-page.yml) which is dependent on previous action.

**Comment by rndquu** [comment]
> It will be removed only after log-app is added to the logging repo, as there are few issues like https://github.com/ubiquity/ubiquibot/issues/676 that will be adding changes to log-app . I will coordinate with contributer/hunter at time of final commit , if they want me to wait and add their changes also or they will make contribution to logging repo later.

I don't understand why we should wait for https://github.com/ubiquity/ubiquibot/issues/676. This [issue](https://github.com/ubiquity/ubiquibot/issues/676) will be simply transferred to the https://github.com/ubiquity/ubiquibot-logging repo and solved there.

> In this PR, there is log-app has no code connected with ubiquibot repo (other than .deployment [file](https://github.com/ubiquity/ubiquibot/blob/development/.github/workflows/deploy-logger-page.yml) which is dependent on previous action.

[This](https://github.com/ubiquity/ubiquibot/tree/development/log-app) whole folder is a log app inside the bot's code. So this [folder](https://github.com/ubiquity/ubiquibot/tree/development/log-app) (along with related code) should be removed from the https://github.com/ubiquity/ubiquibot repo.

**Review by cuddle-dev — CHANGES_REQUESTED** [review]
I don't understand about the changes.

1/ Why do we want to deploy log-app to cloudflare in ubiquibot repo? -- doesn't make sense. It should be in the same repository: ubiquity/ubiquibot-logging

2/ I guess that's fine to remove log-app folder and relevant stuff from ubiquibot.

As a issue creator, would you @rndquu give me better understanding?

**Comment by rndquu** [comment]
> 1/ Why do we want to deploy log-app to cloudflare in ubiquibot repo? -- doesn't make sense. It should be in the same repository: ubiquity/ubiquibot-logging

Yes, it should be in a [separate repo](https://github.com/ubiquity/ubiquibot-logging) as stated in the issue's description

> 2/ I guess that's fine to remove log-app folder and relevant stuff from ubiquibot.

Yes, it is also stated in the issue's description

> As a issue creator, would you @rndquu give me better understanding?

I don't know what else to add :)

**Comment by whilefoo** [comment]
closing due to inactivity

**Pull request closed without merging**
