### PR TITLE
fix: use bot penalty

### PR DESCRIPTION
**Pull request by Keyrxng**
Checks if the bot penalty comment created at is more than last activity, if so it returns only the delivery timeline else it will unnassign.

Resolves https://github.com/ubiquity/ubiquibot/issues/681

Example https://github.com/Keyrxng/UbiquityBotTesting/issues/11#issuecomment-1712968225

For testing purposes I added the penalty comment myself to workaround not having setup the backend fully yet but I believe it shows the logic working as intended.

My issue is old enough that it was unassigning me as you'll see with the bot doing so in the interaction list above the comments, after the fix it no longer unassigns.

### CODE REVIEW

**Comment by pavlovcik** [comment]
I believe that it makes a lot more sense to check the timestamp of when it was reopened, instead of the follow up comment.

**Comment by 0xcodercrane** [comment]
should get the timestamp from the reopened event and recalculate the deadline @Keyrxng

**Review by 0xcodercrane — CHANGES_REQUESTED** [review]
you should get the timestamp from the reopened event and recalculate the deadline @Keyrxng

**Review by wannacfuture — COMMENTED** [review]
I think this issue's purpose is to make bot to not unassign hunter right after manual assigning.

I can't see it on your QA, @Keyrxng 
Would you mind posting a valid one?

Or we can do it in a more simple way.
https://github.com/ubiquity/ubiquibot/pull/759/files
@pavlovcik , @0xcodercrane

**Comment by Keyrxng** [comment]
> I think this issue's purpose is to make bot to not unassign hunter right after manual assigning.
> 
> I can't see it on your QA, @Keyrxng Would you mind posting a valid one?
> 
> Or we can do it in a more simple way. https://github.com/ubiquity/ubiquibot/pull/759/files @pavlovcik , @0xcodercrane

I had read the issue as the bot unassigning once an old issue has been reopened which forced the bot to unassign due to it being over the deliverable date, the manual assign being automatically unassigned thing is just a by-product of this. 

After my impl the bot stopped trying to unassign me after I manually reassigned.

But by all means if your linked pr solves this issue then you take it

**Comment by 0xcodercrane** [comment]
> I think this issue's purpose is to make bot to not unassign hunter right after manual assigning.
> 
> I can't see it on your QA, @Keyrxng Would you mind posting a valid one?
> 
> Or we can do it in a more simple way. https://github.com/ubiquity/ubiquibot/pull/759/files @pavlovcik , @0xcodercrane

The purpose is to reset the deadline when you reopen the closed issue  + stop unassigning the hunter at that time.

**Comment by 0xcodercrane** [comment]
took a look at your PR for this task. It would also work but you have been solving another issue. @wannacfuture

**Comment by wannacfuture** [comment]
> took a look at your PR for this task. It would also work for this issue but you have been solving another issue. @wannacfuture.

the root cause of the PR's related issue also contains fixing deadline.

**Comment by Keyrxng** [comment]
> 2/ The assignee should still be Keyrxng.

This feels sort of wrong, you wanna at least split it @wannacfuture?

**Comment by wannacfuture** [comment]
> > 2/ The assignee should still be Keyrxng.
> 
> This feels sort of wrong, you wanna at least split it @wannacfuture?

Just take it. @Keyrxng can think as hotfix. no problem.

**Comment by Keyrxng** [comment]
Humbled mate, I appreciate it

**Comment by 0xcodercrane** [comment]
Thanks both for the great swarming lol

**Review by 0xcodercrane — APPROVED** [review]
This would work. merging

**Pull request merged**
