### PR TITLE
feat: table font in monospace

### LINKED ISSUE #467: Monospace Assign Table Font
> <table>
>   <tr>
>     <td style="border:1px solid"></td>
>     <td style="border:1px solid"></td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Deadline</td>
>     <td style="border:1px solid">Mon, 03 Jul 2023 20:26:35 GMT</td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Registered Wallet</td>
>     <td style="border:1px solid">0xb87d1713f2fade89fe9de557a2e37d10f006a5d1</td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Payment Multiplier</td>
>     <td style="border:1px solid">2.00</td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Multiplier Reason</td>
>     <td style="border:1px solid">testing </td>
>   </tr>
>   <tr>
>     <td style="border:1px solid">Total Bounty</td>
>     <td style="border:1px solid">25 USD</td>
>   </tr>
>   </table>

I just realized this was implemented with a mistake. It should all be in a monospace font.  

_Originally posted by @pavlovcik in https://github.com/ubiquibot/staging/issues/41#issuecomment-1621896888_

### PR DESCRIPTION
**Pull request by EtherealGlow**
Resolves #467

### CODE REVIEW

**Comment by 0xcodercrane** [comment]
Need a QA link

**Comment by Draeieg** [comment]
[This](https://github.com/ubiquibot/staging/issues/76#issuecomment-1654863747) doesn't look right to me @pavlovcik @0xcodercrane

**Comment by 0xcodercrane** [comment]
> [This](https://github.com/ubiquibot/staging/issues/76#issuecomment-1654863747) doesn't look right to me @pavlovcik @0xcodercrane

You tested it by switching the publish link to the PR one on staging right?

**Comment by Draeieg** [comment]
> > [This](https://github.com/ubiquibot/staging/issues/76#issuecomment-1654863747) doesn't look right to me @pavlovcik @0xcodercrane
> 
> You tested it by switching the publish link to the PR one on staging right?

Yes, you can look at the first assign I did without switching to the preview and then the one I linked with the publish link on, the font changes but it looks as if it was on smaller Window

**Comment by Draeieg** [comment]
idk if I'm blind but it seems [the same](https://github.com/ubiquibot/staging/issues/76#issuecomment-1656911234) as before @0xcodercrane @pavlovcik

**Comment by EtherealGlow** [comment]
idk i tried, it should have worked

**Pull request closed without merging**
