### PR TITLE
fix: allow regex

### PR DESCRIPTION
**Pull request by whilefoo**
This fixed the allow regex to allow `-` characters in the username.

### CODE REVIEW

**Review by 0xcodercrane — CHANGES_REQUESTED** [review]
const body = "/allow set-multiplier @ubiquibty*addd true"
const regex = /^\/allow\s+set-(\S+)\s+@([\w-]+)\s+(true|false)\s*$/;
body.match(regex)

result: null

**Comment by wannacfuture** [comment]
const body = "/allow set-multiplier @ubiquibtyaddd true"
const regex = /^\/allow set-(\S+)\s@(\S+)\s(true|false)$/;
body.match(regex)

lol it works.

**Comment by 0xcodercrane** [comment]
> const body = "/allow set-multiplier @ubiquibtyaddd true" const regex = /^/allow set-(\S+)\s@(\S+)\s(true|false)$/; body.match(regex)
> 
> lol it works.

Yes!

**Comment by 0xcodercrane** [comment]
ok I am doing an admin action for both PRs then.

**Pull request closed without merging**
