### PR TITLE
feat: permits row security setup

### LINKED ISSUE #547: Set up supabase policies
Depends on https://github.com/ubiquity/ubiquibot/issues/546

We have [plans](https://github.com/ubiquity/pay.ubq.fi/issues/110) for reading permit URLs from supabase DB instead of parsing github comments.

We're going to hardcode supabase API key in the frontend code so we need to restrict access to most of the supabase tables. In other words we should setup [supabase policies](https://supabase.com/docs/guides/auth/row-level-security) in the way so that the hardcoded supabase API key could **only** read from the permit URLs table **without access** to all other tables.

### PR DESCRIPTION
**Pull request by seprintour**
Resolves #547

- Only permits returns data, every other table returns `[]`
- Only select is enabled, no writes
- I assumed RLS is enabled for all tables before now

@pavlovcik @rndquu 

Here's a fetch snippet for my permit 
```js
fetch('https://qzfjblxdroqrmlheoajw.supabase.co/rest/v1/permits?select=*', {
    headers: {
        'apikey': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6ZmpibHhkcm9xcm1saGVvYWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODA4NTMwMzMsImV4cCI6MTk5NjQyOTAzM30.BM_qkpX-egNdiMc0PDO_34bIaXHB7ewnr2k4U2hGFMM',
        'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6ZmpibHhkcm9xcm1saGVvYWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODA4NTMwMzMsImV4cCI6MTk5NjQyOTAzM30.BM_qkpX-egNdiMc0PDO_34bIaXHB7ewnr2k4U2hGFMM'
    }
});
```

Trying to alter tables will fail

```js
fetch('https://qzfjblxdroqrmlheoajw.supabase.co/rest/v1/permits', {
    method: 'POST',
    headers: {
        'apikey': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6ZmpibHhkcm9xcm1saGVvYWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODA4NTMwMzMsImV4cCI6MTk5NjQyOTAzM30.BM_qkpX-egNdiMc0PDO_34bIaXHB7ewnr2k4U2hGFMM',
        'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6ZmpibHhkcm9xcm1saGVvYWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODA4NTMwMzMsImV4cCI6MTk5NjQyOTAzM30.BM_qkpX-egNdiMc0PDO_34bIaXHB7ewnr2k4U2hGFMM',
        'Content-Type': 'application/json',
        'Prefer': 'return=minimal'
    },
    // body: '{ "issue_id": "678678678", "bounty_hunter_id": "3243243424" }',
    body: JSON.stringify({
        'issue_id': '678678678',
        'bounty_hunter_id': '3243243424'
    })
});
```

### CODE REVIEW

**Review by whilefoo — CHANGES_REQUESTED** [review]
Looks good, I verified that it's working correctly. 

@seprintour could you modify the sql to enable RLS for other tables because it's better to do it programmatically than manually.

**Comment by seprintour** [comment]
> Looks good, I verified that it's working correctly.
> 
> @seprintour could you modify the sql to enable RLS for all other tables because it's better to do it programmatically than manually.

Okay, i just assumed its already been enabled.. i made a commit to add enable RLS for all tables.

**Review by whilefoo — APPROVED** [review]

**Comment by seprintour** [comment]
@0xcodercrane

**Comment by seprintour** [comment]
@0xcodercrane

**Comment by 0xcodercrane** [comment]
https://github.com/ubiquity/ubiquibot/issues/547#issuecomment-1667328772

commented here.

**Comment by Draeieg** [comment]
> [#547 (comment)](https://github.com/ubiquity/ubiquibot/issues/547#issuecomment-1667328772)
> 
> commented here.

does this mean you approve and is ready for QA?

**Comment by 0xcodercrane** [comment]
> does this mean you approve and is ready for QA?

will leave another comment/approval there and keep u updated here

**Comment by seprintour** [comment]
> > [#547 (comment)](https://github.com/ubiquity/ubiquibot/issues/547#issuecomment-1667328772)
> > commented here.
> 
> does this mean you approve and is ready for QA?

I think the PR description works as QA already, a QA issue won't do any help..

**Review by 0xcodercrane — APPROVED** [review]

**Comment by pavlovcik** [comment]
I'm not sure what to do with this pull request. Should we just run the SQL code in Supabase and see if it works? @rndquu you said this is [a four hour](https://github.com/ubiquity/ubiquibot/issues/547#issuecomment-1657079985) task but this is a very small deliverable. Please check this.

**Review by pavlovcik — APPROVED** [review]
Tests check out.

**Comment by seprintour** [comment]
This is a small deliverable, just automates the RLS setup.. should be pretty easy to test, it works as expected

**Review by rndquu — APPROVED** [review]

**Comment by rndquu** [comment]
> I'm not sure what to do with this pull request. Should we just run the SQL code in Supabase and see if it works? @rndquu you said this is [a four hour](https://github.com/ubiquity/ubiquibot/issues/547#issuecomment-1657079985) task but this is a very small deliverable. Please check this.

> I'm not sure what to do with this pull request. Should we just run the SQL code in Supabase and see if it works?

We should merge the current PR and run the SQL migration

> @rndquu you said this is [a four hour](https://github.com/ubiquity/ubiquibot/issues/547#issuecomment-1657079985) task but this is a very small deliverable. Please check this.

This issue implied:
- checking the [docs](https://supabase.com/docs/guides/auth/row-level-security)
- checking whether RLS solves the original issue
- implementing a solution

So this issue should normally take 2-4 hours for a bounty hunter to solve it. At the time of the issue creation we didn't have the `<4 hours` label hence the `<1 Day` time label was applied.

**Comment by pavlovcik** [comment]
@seprintour out of curiously how long did it take you? Don't worry- the reward is already yours to keep!

**Comment by seprintour** [comment]
> @seprintour out of curiously how long did it take you? Don't worry- the reward is already yours to keep!

Took me about 2 hours if i can remember, i had to look through the videos on docs (was pretty clear) but most of it was spent testing to make sure creates, update and delete don't get through to the DB

**Pull request merged**
