### PR TITLE
feat: QA automation yml

### PR DESCRIPTION
**Pull request by wannacfuture**
Resolves https://github.com/ubiquibot/QA-Improvements/issues/1

### CODE REVIEW

**Comment by wannacfuture** [comment]
@pavlovcik , @0xcodercrane . Could you review this one?

**Comment by 0xcodercrane** [comment]
@wannacfuture would you let us know when it is ready? I can see the commits you pushed after the review request. Please ping us again for the confirmation.

**Comment by wannacfuture** [comment]
Ready for review.

**Comment by pavlovcik** [comment]
Can you post proof that this works as expected? I couldn't find any on your fork.

**Comment by wannacfuture** [comment]
> Can you post proof that this works as expected? I couldn't find any on your fork.

It worked.(I remember I have sent the video in my intro group chat.😉 https://t.me/c/1963922864/43 )
https://github.com/wannacfuture/Battleship/blob/main/.github/workflows/pr_reviewer_changed.yml
I only want to know that the github token which I'm currently using in the yml of this pr is correct.
Looking forward hearing from you.

**Comment by pavlovcik** [comment]
> I only want to know that the github token which I'm currently using in the yml of this pr is correct.
Looking forward hearing from you.😊

So @0xcodercrane we should make a tightly scoped token for the bot to be able to edit the projects right?

**Comment by 0xcodercrane** [comment]
> > I only want to know that the github token which I'm currently using in the yml of this pr is correct.
> > Looking forward hearing from you.😊
> 
> So @0xcodercrane we should make a tightly scoped token for the bot to be able to edit the projects right?

yes. but lets see how it goes with app token

**Comment by pavlovcik** [comment]
I just checked and looks like we would need to create a brand new app in order to modify permissions. I don't see how we can make an access token with scoped permissions.

**Pull request merged**
