### PR TITLE
fix: regex errors and update index.ts

### LINKED ISSUE #489: Query User Information (Wallet Address, Multiplier)
I have been doing some manual payouts lately and realized that sometimes it's nice to be able to quickly identify a user's `multiplier` and `wallet` address without superuser access to the global bot database!

We should have a new command to view a user's settings. 

`/query @user`

Unless there is a better, more expressive command name than "query" 

---

> I'll need to send some xDAI to both participants because this was my fault for not ensuring that the bounty is valid. 

> https://gnosisscan.io/tx/0x3162608e9e18f71b4b29b0780904b664d160d0d79b0f761569f0d590b5f16044 @me505 
> https://gnosisscan.io/tx/0xbb9e74ab8951f5cc45fb38dd1d56f7e04e3c0ba6db98bfbaf58bfe63043d950a @AnakinSkywalkeer

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/562#issuecomment-1630854865_

### PR DESCRIPTION
**Pull request by me505**
Resolves #489 
this is a hotfix

### CODE REVIEW

**Review by pavlovcik — APPROVED** [review]

**Comment by devpanther** [comment]
@me505 i fixed this here

https://github.com/ubiquity/ubiquibot/blob/79dc7a54658890ba5f063ef88e1343c24fe34201/src/handlers/comment/handlers/query.ts#L25

Your regex was still wrong, you might want to set up the bot on your repo so you can test like this https://github.com/two-two-test/second/issues/1#issuecomment-1657216161

**Comment by pavlovcik** [comment]
@me505 can you fix?

**Comment by devpanther** [comment]
> @me505 can you fix?

@pavlovcik i already fixed it on my closed PR

**Comment by devpanther** [comment]
Made sure it works here https://github.com/two-two-test/second/issues/1#issuecomment-1657218890

**Comment by pavlovcik** [comment]
So I can close the issue again?

**Comment by devpanther** [comment]
> So I can close the issue again? Can you link me a working QA example?

Here https://github.com/two-two-test/second/issues/1#issuecomment-1657218890

If you look up, you'd see the progress before it got fixed

**Pull request merged**
