### PR TITLE
Hotfix of /assign issue

### PR DESCRIPTION
**Pull request by 0xcodercrane**
Resolves # https://github.com/ubiquity/ubiquibot/issues/430

### CODE REVIEW

**Comment by pavlovcik** [comment]
Why do you have so many commits from a hotfix you worked on today? You should redo this pull request and base it off of `development` HEAD.

**Comment by 0xcodercrane** [comment]
The root cause of /assign issue is 
1/ we were not always responding with the failure reason. so nobody knew what happened.
2/ we have a couple of improvements to handle the response message but not synced to `main` branch

so if both https://github.com/ubiquity/ubiquibot/pull/436 and https://github.com/ubiquity/ubiquibot/pull/422 are merged, /assign issue should be fixed.

**Review by pavlovcik — COMMENTED** [review]
Seems like this isn't fixing anything. However it appears to have a new type of log, and adding two new return comments.

**Comment by 0xcodercrane** [comment]
> Why do you have so many commits from a hotfix you worked on today? You should redo this pull request and base it off of `development` HEAD.

Most of them have been generated by merging `development` to `hotfix-assign-issue`. please check the files changed.

**Comment by 0xcodercrane** [comment]
> Seems like this isn't fixing anything. However it appears to have a new type of log, and adding two new return comments.

please take a look at the second reason that I posted

**Pull request merged**
